chore: renamed createElement to createTestElement
Using createElement apparently fails the eslint-plugin-react@7.20.4:

```
TypeError: Cannot read property 'callee' of null
Occurred while linting react-md/packages/utils/src/positioning/__tests__/getElementRect.ts:3
```

I should probably open a bug or something since `createElement` appears
to be a reserved word now.